# -*- coding: utf-8 -*-
"""
Mi conjetura sobre que nombra cada etiqueta del grafo.

Cadena vacia = no tengo conjetura. La marca «TEMA» significa que creo que la
etiqueta NO nombra una coleccion de objetos matematicos, sino un tema, una
tecnica o un resultado — y que por tanto no admite la maquinaria categorica.
"""

CONJETURAS: dict[str, str] = {
    # ── fundacionales ───────────────────────────────────────────────────────
    "zfc-axioms": "TEMA — los axiomas son enunciados, no objetos",
    "ordinals": "un ordinal",
    "cat-basics": "una categoría (pequeña)",
    "functors": "¿un funtor? ¿entre qué dos categorías fijas? ¿o TEMA?",
    "nat-trans": "una transformación natural entre dos funtores fijos",
    "limits": "¿un cono límite? ¿o TEMA — la técnica de tomar límites?",
    "fol-deduction": "TEMA — una regla de deducción, no un objeto",
    "fol-metatheory": "TEMA",
    "cic": "¿un tipo del Cálculo de Construcciones Inductivas?",
    "lean-kernel": "TEMA — un verificador, no una categoría",

    # ── álgebra ─────────────────────────────────────────────────────────────
    "group-theory": "un grupo",
    "abelian-groups": "un grupo abeliano",
    "subgroups-cosets": "TEMA, o quizá: un subgrupo de un grupo dado",
    "quotient-groups": "un grupo cociente",
    "group-homomorphisms": "TEMA — son los morfismos, no los objetos",
    "group-actions": "un G-conjunto (conjunto con acción de un grupo)",
    "sylow-theory": "TEMA — un teorema",
    "free-groups": "un grupo libre",
    "solvable-groups": "un grupo resoluble",
    "representation-theory": "una representación de un grupo",
    "character-theory": "un carácter de una representación",
    "ring-theory": "un anillo",
    "commutative-algebra": "un anillo conmutativo",
    "ideals-quotient-rings": "un ideal, o un anillo cociente",
    "polynomial-rings": "un anillo de polinomios",
    "noetherian-rings": "un anillo noetheriano",
    "unique-factorization": "un dominio de factorización única",
    "localization": "una localización de un anillo",
    "field-theory": "un cuerpo",
    "field-extensions": "una extensión de cuerpos",
    "finite-fields": "un cuerpo finito",
    "splitting-fields": "un cuerpo de descomposición",
    "galois-theory": "una extensión de Galois, o su grupo",
    "module-theory": "un módulo sobre un anillo",
    "projective-injective-modules": "un módulo proyectivo o inyectivo",
    "tensor-products": "un producto tensorial de módulos",
    "exact-sequences": "una sucesión exacta",
    "homological-algebra": "¿un complejo de cadenas sobre un anillo?",
    "linear-algebra": "un espacio vectorial",
    "inner-product-spaces": "un espacio con producto interno",
    "bilinear-forms": "una forma bilineal",
    "eigen-theory": "TEMA, o quizá: un operador con su espectro",
    "canonical-forms": "TEMA — formas normales de matrices",

    # ── teoría de números ───────────────────────────────────────────────────
    "elementary-number-theory": "TEMA, o quizá: el anillo de los enteros",
    "divisibility-gcd": "TEMA",
    "modular-arithmetic": "un anillo de enteros módulo n",
    "prime-factorization": "TEMA",
    "quadratic-residues": "TEMA",
    "diophantine-equations": "TEMA",
    "algebraic-number-theory": "un cuerpo de números, o su anillo de enteros",
    "number-fields": "un cuerpo de números",
    "ideal-class-group": "el grupo de clases de un cuerpo de números",
    "p-adic-valuations": "una valoración, o un cuerpo p-ádico",
    "analytic-number-theory": "TEMA",
    "riemann-zeta": "TEMA — una función concreta",
    "prime-number-theorem": "TEMA — un teorema",
    "arithmetic-geometry": "¿un esquema sobre un anillo de enteros?",

    # ── topología ───────────────────────────────────────────────────────────
    "point-set-topology": "un espacio topológico",
    "metric-spaces": "un espacio métrico",
    "compactness": "TEMA — una propiedad, no un objeto",
    "connectedness": "TEMA — una propiedad",
    "separation-axioms": "TEMA — propiedades",
    "algebraic-topology": "¿un espacio topológico? ¿un CW-complejo?",
    "fundamental-group": "el grupo fundamental de un espacio punteado",
    "covering-spaces": "un espacio recubridor",
    "homology": "¿un grupo abeliano graduado?",
    "cohomology": "¿un grupo abeliano graduado?",
    "homotopy-theory": "¿un espacio topológico, salvo homotopía?",
    "homotopy-type-theory": "un tipo en HoTT",
    "geometric-topology": "una variedad de dimensión baja",
    "differential-topology": "una variedad suave",
    "planar-graphs": "un grafo planar",
    "graph-theory": "un grafo",

    # ── geometría ───────────────────────────────────────────────────────────
    "euclidean-geometry": "TEMA",
    "triangle-geometry": "TEMA",
    "circle-geometry": "TEMA",
    "projective-geometry": "un espacio proyectivo",
    "projective-varieties": "una variedad proyectiva",
    "affine-varieties": "una variedad afín",
    "algebraic-geometry": "¿un esquema? ¿una variedad?",
    "differential-geometry": "una variedad diferenciable",
    "riemannian-geometry": "una variedad riemanniana",
    "symplectic-geometry": "una variedad simpléctica",
    "smooth-manifolds": "una variedad suave",
    "differential-forms": "una forma diferencial",
    "complex-geometry": "una variedad compleja",
    "schemes": "un esquema",

    # ── análisis ────────────────────────────────────────────────────────────
    "real-analysis": "TEMA, o quizá: los números reales",
    "sequences-series": "TEMA",
    "limits-continuity": "TEMA",
    "differentiation": "TEMA",
    "riemann-integration": "TEMA",
    "lebesgue-integration": "TEMA",
    "measure-theory": "un espacio de medida",
    "functional-analysis": "un espacio vectorial topológico",
    "banach-spaces": "un espacio de Banach",
    "hilbert-spaces": "un espacio de Hilbert",
    "operator-theory": "un operador acotado, o un álgebra de operadores",
    "spectral-theory": "TEMA",
    "complex-analysis": "TEMA, o quizá: una superficie de Riemann",
    "holomorphic-functions": "una función holomorfa",
    "contour-integration": "TEMA — una técnica",
    "residue-theorem": "TEMA — un teorema",
    "conformal-maps": "una aplicación conforme",
    "harmonic-analysis": "TEMA",
    "pde-techniques": "TEMA — técnicas",
    "variational-methods": "TEMA — técnicas",

    # ── probabilidad ────────────────────────────────────────────────────────
    "probability-theory": "un espacio de probabilidad",
    "random-variables": "una variable aleatoria",
    "conditional-expectation": "TEMA, o quizá: una esperanza condicional",
    "martingale-theory": "una martingala",
    "stochastic-processes": "un proceso estocástico",
    "brownian-motion": "TEMA — un proceso concreto",
    "markov-chains": "una cadena de Markov",
    "limit-theorems": "TEMA — teoremas",
    "probabilistic-method": "TEMA — una técnica de demostración",

    # ── combinatoria ────────────────────────────────────────────────────────
    "enumerative-combinatorics": "TEMA",
    "generating-functions": "una función generatriz",
    "inclusion-exclusion": "TEMA — una técnica",
    "partitions": "una partición",
    "ramsey-theory": "TEMA",
    "extremal-combinatorics": "TEMA",
    "graph-coloring": "TEMA",
    "matching-theory": "TEMA",
    "algebraic-combinatorics": "TEMA",
    "discrete-optimization": "TEMA",

    # ── lógica y computación ────────────────────────────────────────────────
    "model-theory": "una estructura de primer orden",
    "proof-theory": "TEMA",
    "sequent-calculus": "TEMA — un sistema de reglas",
    "incompleteness": "TEMA — un teorema",
    "compactness-theorem": "TEMA — un teorema",
    "ultraproducts": "un ultraproducto de estructuras",
    "computability-theory": "TEMA",
    "recursion-theory": "TEMA",
    "turing-machines": "una máquina de Turing",
    "computational-complexity": "TEMA",
    "np-completeness": "TEMA",
    "algorithm-analysis": "TEMA",
    "lambda-calculus": "un término del cálculo lambda",
    "formal-verification": "TEMA",
    "set-theory": "un conjunto",
    "descriptive-set-theory": "un conjunto boreliano o proyectivo",
    "large-cardinals": "un cardinal grande",
    "cardinal-arithmetic": "TEMA",
    "forcing": "TEMA — una técnica",

    # ── teoría de categorías ────────────────────────────────────────────────
    "universal-properties": "TEMA — un patrón de definición",
    "adjunctions": "una adjunción entre dos funtores",
    "monads": "una mónada sobre una categoría",
    "yoneda-lemma": "TEMA — un lema",
    "abelian-categories": "una categoría abeliana",
    "homological-algebra-cat": "¿una categoría abeliana? ¿o TEMA?",
    "higher-category-theory": "una n-categoría",
    "topos-theory": "un topos",
    "kan-extensions": "una extensión de Kan",
    "duality-theory": "TEMA",
    "ergodic-theory": "un sistema dinámico con medida invariante",
    "linear-programming": "TEMA",
    "convex-optimization": "TEMA",
}

#: Prefijos cuyas etiquetas son, con casi total seguridad, TEMA y no categoría.
PREFIJOS_TEMA = ("tactic-", "strategy-")
