# -*- coding: utf-8 -*-
"""Nodos de COBERTURA generados desde la taxonomia de Mathlib.

GENERADO por scripts/generar_nodos_mathlib.py — no editar a mano sin
anotarlo: una regeneracion lo pisa. Se versiona como codigo, y no como
JSON, para que se pueda leer y corregir en la revision.

ESTOS NODOS NO ESTAN INTERPRETADOS. Los 173 de math_domains.py llevan un
veredicto categorico —«un objeto es un grupo, las flechas son
homomorfismos»— decidido a mano. Estos solo dicen DONDE VIVE algo en
Mathlib, con que vocabulario se habla de ello y de que depende segun el
DAG de imports. Por eso llevan `interpretado=False`: para que nada
afirme sobre ellos lo que nadie ha decidido.

Las dependencias SI son reales: salen de los imports de Mathlib, que son
aciclicos y estan en el fuente. No son curacion humana y no pueden estar
al reves.

Umbral: 500 teoremas. Profundidad: 2.
"""
from dataclasses import dataclass, field


@dataclass
class NodoCobertura:
    """Un concepto de Mathlib que el grafo no tenia."""
    id: str
    name: str
    description: str
    pillar: str
    level: int
    category: str
    modulo: str
    teoremas: int
    dependencies: list = field(default_factory=list)
    keywords: list = field(default_factory=list)


NODOS_MATHLIB = [
    NodoCobertura(
        id='mathlib-algebra-order',
        name='Algebra · Order',
        description="algebra order: Ordered scalar multiplication and vector addition; Ordered algebras; Chebyshev's sum inequality; Conditionally complete linear ordered fields; `Disjointed` for functions on a `SuccAddOrder`; Lemmas about `invOf` in ordered (semi)rings.",
        pillar='SET', level=2, category='algebra',
        modulo='Mathlib.Algebra.Order', teoremas=5140,
        dependencies=['mathlib-algebra-bigoperators', 'mathlib-algebra-star', 'mathlib-data-ennreal', 'mathlib-data-fin', 'mathlib-data-finset', 'mathlib-data-finsupp'],
        keywords=['smul', 'comp', 'perm', 'left', 'round', 'right', 'kstar', 'induced', 'monovary', 'antivary', 'cast', 'left₀', 'right₀', 'self', 'card', 'strict', 'mono', 'zero', 'algebra', 'cancel', 'nonneg', 'forall', 'rearrangement', 'ordered'],
    ),
    NodoCobertura(
        id='mathlib-analysis-specialfunctions',
        name='Analysis · SpecialFunctions',
        description="analysis special functions: Inverse of the cosh function; The arithmetic-geometric mean; Inverse of the sinh function; Inverse of the tanh function; Bernstein approximations and Weierstrass' theorem; Properties of Shannon q-ary entropy and binary entropy functions",
        pillar='SET', level=2, category='analysis',
        modulo='Mathlib.Analysis.SpecialFunctions', teoremas=3906,
        dependencies=['mathlib-algebra-bigoperators', 'mathlib-algebra-order', 'mathlib-algebra-polynomial', 'mathlib-analysis-asymptotics', 'mathlib-analysis-complex', 'mathlib-analysis-convex'],
        keywords=['arsinh', 'entropy', 'deriv', 'zero', 'cexp', 'strict', 'arcosh', 'artanh', 'tendsto', 'sequences', 'fderiv', 'qary', 'comp', 'analytic', 'nhds', 'smul', 'rexp', 'const', 'little', 'continuous', 'differentiable', 'comap', 'cosh', 'sinh'],
    ),
    NodoCobertura(
        id='mathlib-data-set',
        name='Data · Set',
        description='Basic properties of sets Sets in Lean are homogeneous; all their elements have the same type. Sets whose elements have type X are thus defined as Set X := X → Prop . Note that this function need not be decidable. The definition is in the module Mathlib/Data/Set/Defs.lean . This f',
        pillar='SET', level=2, category='algebra',
        modulo='Mathlib.Data.Set', teoremas=2852,
        dependencies=['mathlib-algebra-bigoperators', 'mathlib-algebra-order', 'mathlib-data-finset', 'mathlib-data-list', 'mathlib-data-nat', 'mathlib-logic-equiv'],
        keywords=['ncard', 'encard', 'subset', 'inter', 'union', 'empty', 'diff', 'nonempty', 'left', 'right', 'univ', 'exists', 'ssubset', 'card', 'accumulate', 'singleton', 'insert', 'comm', 'image', 'zero', 'powerset', 'preimage', 'finite', 'subtype'],
    ),
    NodoCobertura(
        id='mathlib-categorytheory-limits',
        name='CategoryTheory · Limits',
        description='category theory limits: Limits and colimits in comma categories; Limits and the category of (co)cones; Cones and cocones; Connected limits; Creating (co)limits; Limits in the category of elements',
        pillar='CAT', level=2, category='category-theory',
        modulo='Mathlib.CategoryTheory.Limits', teoremas=2834,
        dependencies=['mathlib-algebra-category', 'mathlib-categorytheory-monoidal', 'mathlib-data-fin', 'mathlib-data-finset', 'mathlib-data-nat', 'mathlib-data-set'],
        keywords=['comp', 'cone', 'colimit', 'cocone', 'limit', 'creates', 'initial', 'arrow', 'final', 'shape', 'limits', 'colimits', 'equivalence', 'forget', 'exact', 'structured', 'left', 'extend', 'costructured', 'functor', 'faithful', 'right', 'preserves', 'equiv'],
    ),
    NodoCobertura(
        id='mathlib-algebra-polynomial',
        name='Algebra · Polynomial',
        description='Theory of univariate polynomials This file defines Polynomial R , the type of univariate polynomials over the semiring R , builds a semiring structure on it, and gives basic definitions that are expanded in other files in this directory. Main definitions monomial n a is the polyn',
        pillar='SET', level=2, category='algebra',
        modulo='Mathlib.Algebra.Polynomial', teoremas=2380,
        dependencies=['mathlib-algebra-bigoperators', 'mathlib-algebra-mvpolynomial', 'mathlib-algebra-order', 'mathlib-data-finset', 'mathlib-data-finsupp', 'mathlib-data-int'],
        keywords=['aeval', 'eval', 'finsupp', 'coeff', 'zero', 'monomial', 'prod', 'degree', 'equiv', 'support', 'comp', 'apply', 'multiset', 'smul', 'algebra', 'ring', 'swap', 'cast', 'polynomial', 'tower', 'erase', 'eval₂', 'update', 'coeffs'],
    ),
    NodoCobertura(
        id='mathlib-data-finset',
        name='Data · Finset',
        description='Basic lemmas on finite sets This file contains lemmas on the interaction of various definitions on the Finset type. For an explanation of Finset design decisions, please see Mathlib/Data/Finset/Defs.lean . Main declarations Main definitions Finset.choose : Given a proof h of exis',
        pillar='SET', level=2, category='algebra',
        modulo='Mathlib.Data.Finset', teoremas=2292,
        dependencies=['mathlib-algebra-bigoperators', 'mathlib-algebra-order', 'mathlib-data-fin', 'mathlib-data-finsupp', 'mathlib-data-int', 'mathlib-data-list'],
        keywords=['card', 'erase', 'finset', 'filter', 'union', 'subset', 'univ', 'sdiff', 'inter', 'insert', 'compl', 'disjoint', 'empty', 'ssubset', 'exists', 'list', 'nonempty', 'singleton', 'induction', 'disj', 'equiv', 'image', 'strong', 'left'],
    ),
    NodoCobertura(
        id='mathlib-order-filter',
        name='Order · Filter',
        description='Theory of filters on sets A filter on a type α is a collection of sets of α which contains the whole α , is upwards-closed, and is stable under intersection. They are mostly used to abstract two related kinds of ideas: limits , including finite or infinite limits of sequences, fi',
        pillar='SET', level=2, category='set-theory',
        modulo='Mathlib.Order.Filter', teoremas=2192,
        dependencies=['mathlib-algebra-bigoperators', 'mathlib-algebra-order', 'mathlib-analysis-asymptotics', 'mathlib-data-finset', 'mathlib-data-int', 'mathlib-data-nat'],
        keywords=['eventually', 'inter', 'principal', 'countable', 'frequently', 'cofinite', 'exists', 'cardinal', 'forall', 'generate', 'union', 'separating', 'filter', 'sets', 'compl', 'cocardinal', 'distrib', 'left', 'right', 'countably', 'generated', 'mono', 'congr', 'nonempty'],
    ),
    NodoCobertura(
        id='mathlib-data-nat',
        name='Data · Nat',
        description='Basic operations on the natural numbers This file builds on Mathlib/Data/Nat/Init.lean by adding basic lemmas on natural numbers depending on Mathlib definitions. See note [foundational algebra order theory].',
        pillar='SET', level=2, category='algebra',
        modulo='Mathlib.Data.Nat', teoremas=1916,
        dependencies=['mathlib-algebra-bigoperators', 'mathlib-algebra-order', 'mathlib-algebra-polynomial', 'mathlib-data-fin', 'mathlib-data-finset', 'mathlib-data-finsupp'],
        keywords=['zero', 'list', 'prime', 'succ', 'factors', 'find', 'left', 'count', 'clog', 'right', 'dist', 'greatest', 'self', 'binary', 'indices', 'bodd', 'div2', 'induction', 'shift', "succ'", 'mono', 'hyperoperation', 'test', 'strong'],
    ),
    NodoCobertura(
        id='mathlib-order-interval',
        name='Order · Interval',
        description='Order intervals This file defines (nonempty) closed intervals in an order (see Set.Icc ). This is a prototype for interval arithmetic. Main declarations NonemptyInterval : Nonempty intervals. Pairs where the second element is greater than the first. Interval : Intervals. Either ∅',
        pillar='SET', level=2, category='set-theory',
        modulo='Mathlib.Order.Interval', teoremas=1916,
        dependencies=['mathlib-algebra-order', 'mathlib-data-finset', 'mathlib-data-int', 'mathlib-data-nat', 'mathlib-data-set', 'mathlib-order-hom'],
        keywords=['subset', 'dual', 'self', 'card', 'right', 'left', 'filter', 'finite', 'order', 'pure', 'prod', 'subtype', 'nonempty', 'zero', 'locally', 'insert', 'empty', 'union', 'diff', 'sect', 'finset', 'disjoint', 'cons', 'embedding'],
    ),
    NodoCobertura(
        id='mathlib-measuretheory-integral',
        name='MeasureTheory · Integral',
        description='measure theory integral: Bounding of integrals by asymptotics; Integral average of a function; Integration of bounded continuous functions; Circle Averages; Integral over a circle in `ℂ`; Circle integral transform',
        pillar='SET', level=2, category='probability',
        modulo='Mathlib.MeasureTheory.Integral', teoremas=1871,
        dependencies=['mathlib-algebra-bigoperators', 'mathlib-algebra-order', 'mathlib-analysis-specialfunctions', 'mathlib-order-filter', 'mathlib-order-interval', 'mathlib-topology-continuousmap'],
        keywords=['integrable', 'integral', 'average', 'circle', 'measure', 'laverage', 'norm', 'zero', 'simple', 'func', 'filter', 'congr', 'smul', 'continuous', 'const', 'exists', 'tendsto', 'measurable', 'lintegral', 'union', 'mono', 'deriv', 'within', 'transform'],
    ),
    NodoCobertura(
        id='mathlib-data-list',
        name='Data · List',
        description='Definitions on lists This file contains various definitions on lists. It does not contain proofs about these definitions, those are contained in other files in Data.List',
        pillar='SET', level=2, category='algebra',
        modulo='Mathlib.Data.List', teoremas=1835,
        dependencies=['mathlib-algebra-bigoperators', 'mathlib-algebra-order', 'mathlib-data-fin', 'mathlib-data-multiset', 'mathlib-data-nat', 'mathlib-data-set'],
        keywords=['cons', 'chain', 'last', 'next', 'length', 'head', 'reverse', 'insert', 'append', 'prev', 'elem', 'lookup', 'singleton', 'filter', 'foldl', 'erase', 'drop', 'union', 'exists', 'injective', 'forall', 'replicate', 'keys', 'right'],
    ),
    NodoCobertura(
        id='mathlib-analysis-convex',
        name='Analysis · Convex',
        description='Convex sets In a 𝕜-vector space, we define the following property: Convex 𝕜 s : A set s is convex if for any two points x y ∈ s it includes segment 𝕜 x y . We provide various equivalent versions, and prove that some specific sets are convex. TODO Generalize all this file to affin',
        pillar='SET', level=2, category='analysis',
        modulo='Mathlib.Analysis.Convex', teoremas=1708,
        dependencies=['mathlib-algebra-bigoperators', 'mathlib-algebra-order', 'mathlib-analysis-specialfunctions', 'mathlib-data-list', 'mathlib-data-set', 'mathlib-grouptheory-groupaction'],
        keywords=['convex', 'wbtw', 'affine', 'sbtw', 'hull', 'left', 'right', 'center', 'mass', 'segment', 'const', 'smul', 'image', 'vadd', 'trans', 'exists', 'zero', 'vsub', 'interior', 'lipschitz', 'span', 'univ', 'preimage', 'card'],
    ),
    NodoCobertura(
        id='mathlib-topology-order',
        name='Topology · Order',
        description='Ordering on topologies and (co)induced topologies Topologies on a fixed type α are ordered, by reverse inclusion. That is, for topologies t₁ and t₂ on α , we write t₁ ≤ t₂ if every set open in t₂ is also open in t₁ . (One also calls t₁ finer than t₂ , and t₂ coarser than t₁ .) An',
        pillar='SET', level=2, category='topology',
        modulo='Mathlib.Topology.Order', teoremas=1486,
        dependencies=['mathlib-data-set', 'mathlib-order-filter', 'mathlib-order-hom', 'mathlib-order-interval', 'mathlib-topology-continuousmap'],
        keywords=['nhds', 'exists', 'continuous', 'open', 'induced', 'generate', 'from', 'image', 'tendsto', 'subset', 'discrete', 'topology', 'coinduced', 'basis', 'forall', 'closure', 'order', 'countable', 'closed', 'within', 'frontier', "nhds'", 'compact', 'interior'],
    ),
    NodoCobertura(
        id='mathlib-analysis-complex',
        name='Analysis · Complex',
        description='Normed space structure on ℂ . This file gathers basic facts of analytic nature on the complex numbers. Main results This file registers ℂ as a normed field, expresses basic properties of the norm, and gives tools on the real vector space structure of ℂ . Notably, it defines the f',
        pillar='SET', level=2, category='analysis',
        modulo='Mathlib.Analysis.Complex', teoremas=1366,
        dependencies=['mathlib-algebra-order', 'mathlib-algebra-polynomial', 'mathlib-analysis-asymptotics', 'mathlib-analysis-convex', 'mathlib-analysis-specialfunctions', 'mathlib-data-nat'],
        keywords=['real', 'norm', 'conj', 'complex', 'differentiable', 'integral', 'plane', 'slit', 'circle', 'smul', 'zero', 'angle', 'countable', 'continuous', 'within', 'apply', 'convex', 'stolz', 'tsum', 'equiv', 'char', 'nhds', 'linear', 'covering'],
    ),
    NodoCobertura(
        id='mathlib-categorytheory-monoidal',
        name='CategoryTheory · Monoidal',
        description='category theory monoidal: The category of bimodule objects over a pair of monoid objects.; The category of bimonoids in a braided monoidal category.; Monoidal categories; Half braidings and the Drinfeld center of a monoidal category; Lemmas which are consequences of monoidal cohe',
        pillar='CAT', level=2, category='category-theory',
        modulo='Mathlib.CategoryTheory.Monoidal', teoremas=1316,
        dependencies=['mathlib-algebra-category', 'mathlib-categorytheory-limits'],
        keywords=['tensor', 'whisker', 'left', 'right', 'comon', 'comp', 'comm', 'unitor', 'forget', 'bimod', 'associator', "hom'", 'pentagon', 'assoc', 'counit', 'naturality', 'braided', 'equiv', 'unit', 'comul', 'trivial', 'symm', 'forget₂grp', 'forget₂comm'],
    ),
    NodoCobertura(
        id='mathlib-geometry-euclidean',
        name='Geometry · Euclidean',
        description='Euclidean spaces This file makes some definitions and proves very basic geometrical results about real inner product spaces and Euclidean affine spaces. Results about real inner product spaces that involve the norm and inner product but not angles generally go in Analysis.NormedS',
        pillar='SET', level=2, category='geometry',
        modulo='Mathlib.Geometry.Euclidean', teoremas=1281,
        dependencies=['mathlib-analysis-convex', 'mathlib-analysis-specialfunctions', 'mathlib-topology-instances'],
        keywords=['excenter', 'point', 'dist', 'orthogonal', 'projection', 'circumcenter', 'weights', 'affine', 'span', 'touchpoint', 'vsub', 'altitude', 'exists', 'reflection', 'singleton', 'monge', 'incenter', 'reindex', 'with', 'side', 'perp', 'bisector', 'restrict', 'orthocenter'],
    ),
    NodoCobertura(
        id='mathlib-algebra-lie',
        name='Algebra · Lie',
        description='Lie algebras This file defines Lie rings and Lie algebras over a commutative ring together with their modules, morphisms and equivalences, as well as various lemmas to make these definitions usable. Main definitions LieRing LieAlgebra LieRingModule LieModule LieHom LieEquiv LieMo',
        pillar='SET', level=2, category='algebra',
        modulo='Mathlib.Algebra.Lie', teoremas=1228,
        dependencies=['mathlib-algebra-order', 'mathlib-algebra-polynomial', 'mathlib-data-finset', 'mathlib-data-int', 'mathlib-data-matrix', 'mathlib-grouptheory-groupaction'],
        keywords=['apply', 'equiv', 'symm', 'module', 'linear', 'ideal', 'self', 'single', 'triv', 'comp', 'range', 'incl', 'comap', 'bracket', 'subalgebra', 'zero', 'abelian', 'injective', 'lift', 'smul', 'trans', 'engel', 'cocycle', 'trivial'],
    ),
    NodoCobertura(
        id='mathlib-combinatorics-matroid',
        name='Combinatorics · Matroid',
        description='Matroids A Matroid is a structure that combinatorially abstracts the notion of linear independence and dependence; matroids have connections with graph theory, discrete optimization, additive combinatorics and algebraic geometry. Mathematically, a matroid M is a structure on a se',
        pillar='SET', level=2, category='combinatorics',
        modulo='Mathlib.Combinatorics.Matroid', teoremas=1180,
        dependencies=['mathlib-data-set', 'mathlib-order-interval'],
        keywords=['closure', 'subset', 'basis', 'indep', 'insert', 'ground', 'inter', 'base', 'circuit', 'diff', 'union', 'exists', 'spanning', 'finite', 'forall', 'fund', 'cocircuit', 'rank', 'ssubset', 'singleton', 'superset', 'compl', 'nonempty', 'infinite'],
    ),
    NodoCobertura(
        id='mathlib-algebra-bigoperators',
        name='Algebra · BigOperators',
        description='algebra big operators: Products of associated, prime, and irreducible elements.; Balancing a function; Average over a finset; Results about big operators with values in a field; Big operators and `Fin`; Finite products and sums over types and sets',
        pillar='SET', level=2, category='algebra',
        modulo='Mathlib.Algebra.BigOperators', teoremas=1100,
        dependencies=['mathlib-algebra-order', 'mathlib-data-finset', 'mathlib-data-finsupp', 'mathlib-data-int', 'mathlib-data-list', 'mathlib-data-multiset'],
        keywords=['prod', 'finprod', 'expect', 'cast', 'succ', 'zero', 'univ', 'support', 'finset', 'multiset', 'range', 'finsum', 'equiv', 'list', 'balance', 'distrib', 'single', 'union', 'partial', 'subset', 'cond', 'apply', 'exists', 'comm'],
    ),
    NodoCobertura(
        id='mathlib-algebraicgeometry-ellipticcurve',
        name='AlgebraicGeometry · EllipticCurve',
        description='algebraic geometry elliptic curve: Elliptic curves with same j-invariants are isomorphic; Models of elliptic curves with prescribed j-invariant; Some normal forms of elliptic curves; Reduction of Weierstrass curves over local fields; Change of variables of Weierstrass curves; Wei',
        pillar='SET', level=2, category='geometry',
        modulo='Mathlib.AlgebraicGeometry.EllipticCurve', teoremas=1030,
        dependencies=['mathlib-algebra-mvpolynomial', 'mathlib-algebra-polynomial', 'mathlib-data-fin', 'mathlib-ringtheory-polynomial'],
        keywords=['char', 'zero', 'three', 'change', 'polynomial', 'variable', 'nonsingular', 'short', 'equiv', 'base', 'point', 'eval', 'exists', 'equation', 'some', 'slope', 'basis', 'subtype', 'torsion', 'smul', 'xyideal', 'symm', 'integral', 'relation'],
    ),
    NodoCobertura(
        id='mathlib-algebra-category',
        name='Algebra · Category',
        description='algebra category: The category of Boolean rings; The category of commutative bialgebras over a commutative ring; The category of groups with zero; Category instance for algebras over a commutative ring; The category of R-algebras has all limits; The monoidal category structure on',
        pillar='SET', level=2, category='algebra',
        modulo='Mathlib.Algebra.Category', teoremas=999,
        dependencies=['mathlib-algebra-bigoperators', 'mathlib-algebra-mvpolynomial', 'mathlib-categorytheory-limits', 'mathlib-categorytheory-monoidal', 'mathlib-data-finsupp', 'mathlib-data-int'],
        keywords=['equiv', 'apply', 'comp', 'tensor', 'bialg', 'comm', 'forget₂', 'coalg', 'ulift', 'quot', 'limit', 'cone', 'binary', 'fgmodule', 'functor', 'desc', 'forget', 'unop', 'comon', 'left', 'right', 'colimit', 'product', 'module'],
    ),
    NodoCobertura(
        id='mathlib-ringtheory-polynomial',
        name='RingTheory · Polynomial',
        description='Ring-theoretic supplement of Algebra.Polynomial. Main results MvPolynomial.isDomain : If a ring is an integral domain, then so is its polynomial ring over finitely many variables. Polynomial.isNoetherianRing : Hilbert basis theorem, that if a ring is Noetherian then so is its pol',
        pillar='SET', level=2, category='algebra',
        modulo='Mathlib.RingTheory.Polynomial', teoremas=884,
        dependencies=['mathlib-algebra-mvpolynomial', 'mathlib-algebra-polynomial', 'mathlib-analysis-complex', 'mathlib-analysis-specialfunctions', 'mathlib-data-multiset', 'mathlib-data-nat'],
        keywords=['content', 'zero', 'eval', 'degree', 'ideal', 'derivative', 'poly', 'coeff', 'linear', 'iterate', 'hilbert', 'equiv', 'dickson', 'prim', 'part', 'primitive', 'aeval', 'norm', 'span', 'gauss', 'restriction', 'leading', 'fraction', 'unit'],
    ),
    NodoCobertura(
        id='mathlib-data-multiset',
        name='Data · Multiset',
        description='Multisets Multisets are finite sets with duplicates allowed. They are implemented here as the quotient of lists by permutation. This gives them computational content. This file contains the definition of Multiset and the basic predicates. Most operations have been split off into ',
        pillar='SET', level=2, category='algebra',
        modulo='Mathlib.Data.Multiset', teoremas=867,
        dependencies=['mathlib-algebra-bigoperators', 'mathlib-algebra-order', 'mathlib-data-list', 'mathlib-data-nat', 'mathlib-data-set', 'mathlib-order-hom'],
        keywords=['filter', 'count', 'cons', 'erase', 'bind', 'card', 'dedup', 'zero', 'singleton', 'right', 'subset', 'left', 'ndinsert', 'ndunion', 'ndinter', 'product', 'join', 'nodup', 'antidiagonal', 'list', 'sigma', 'self', 'attach', 'induction'],
    ),
    NodoCobertura(
        id='mathlib-analysis-asymptotics',
        name='Analysis · Asymptotics',
        description='Asymptotics We introduce these relations: IsBigOWith c l f g : "f is big O of g along l with constant c"; f =O[l] g : "f is big O of g along l"; f =Θ[l] g : "f is big O of g along l and vice versa"; f =o[l] g : "f is little o of g along l"; f ~[l] g : f and g are equivalent, i.e.',
        pillar='SET', level=2, category='analysis',
        modulo='Mathlib.Analysis.Asymptotics', teoremas=761,
        dependencies=['mathlib-algebra-polynomial', 'mathlib-analysis-convex', 'mathlib-analysis-specialfunctions', 'mathlib-topology-instances'],
        keywords=['little', 'growth', 'const', 'left', 'owith', 'right', 'tendsto', 'prod', 'trans', 'congr', 'eventually', 'norm', 'zero', 'comp', 'smul', 'equivalent', 'exists', 'nhds', 'self', 'symm', 'nonneg', 'principal', 'theta', 'completion'],
    ),
    NodoCobertura(
        id='mathlib-algebra-mvpolynomial',
        name='Algebra · MvPolynomial',
        description='Multivariate polynomials This file defines polynomial rings over a base ring (or even semiring), with variables from a general type σ (which could be infinite). Important definitions Let R be a commutative ring (or a semiring) and let σ be an arbitrary type. This file creates the',
        pillar='SET', level=2, category='algebra',
        modulo='Mathlib.Algebra.MvPolynomial', teoremas=755,
        dependencies=['mathlib-algebra-bigoperators', 'mathlib-algebra-order', 'mathlib-algebra-polynomial', 'mathlib-data-fin', 'mathlib-data-finsupp', 'mathlib-logic-equiv'],
        keywords=['monomial', 'equiv', 'degree', 'coeff', 'support', 'total', 'degrees', 'coeffs', 'zero', 'left', 'option', 'succ', 'polynomial', 'rename', 'symm', 'iter', 'comp', 'comap', 'single', 'derivation', 'empty', 'eval', 'apply', 'injective'],
    ),
    NodoCobertura(
        id='mathlib-algebra-star',
        name='Algebra · Star',
        description='Star monoids, rings, and modules We introduce the basic algebraic notions of star monoids, star rings, and star modules. A star algebra is simply a star ring that is also a star module. These are implemented as "mixin" typeclasses, so to summon a star ring (for example) one needs',
        pillar='SET', level=2, category='algebra',
        modulo='Mathlib.Algebra.Star', teoremas=741,
        dependencies=['mathlib-algebra-bigoperators', 'mathlib-algebra-order', 'mathlib-data-int', 'mathlib-data-set', 'mathlib-linearalgebra-tensorproduct'],
        keywords=['star', 'unital', 'apply', 'conjneg', 'intrinsic', 'subalgebra', 'adjoin', 'self', 'adjoint', 'center', 'comp', 'comm', 'symm', 'prod', 'centralizer', 'ring', 'part', 'subtype', 'range', 'inclusion', 'equiv', 'zero', 'smul', 'copy'],
    ),
    NodoCobertura(
        id='mathlib-grouptheory-perm',
        name='GroupTheory · Perm',
        description='Extra lemmas about permutations This file proves miscellaneous lemmas about Equiv.Perm . TODO Most of the content of this file was moved to Mathlib/Algebra/Group/End.lean in https://github.com/leanprover-community/mathlib4/pull/22141. It would be good to merge the remaining lemma',
        pillar='SET', level=2, category='algebra',
        modulo='Mathlib.GroupTheory.Perm', teoremas=681,
        dependencies=['mathlib-algebra-order', 'mathlib-data-finset', 'mathlib-data-int', 'mathlib-data-list', 'mathlib-data-set', 'mathlib-grouptheory-groupaction'],
        keywords=['perm', 'support', 'cycle', 'sign', 'apply', 'swap', 'range', 'form', 'disjoint', 'card', 'prod', 'stabilizer', 'symm', 'closure', 'subtype', 'self', 'conj', 'zpow', 'trans', 'centralizer', 'type', 'zero', 'decompose', 'rotate'],
    ),
    NodoCobertura(
        id='mathlib-data-matrix',
        name='Data · Matrix',
        description='Matrices This file contains basic results on matrices including bundled versions of matrix operators. Implementation notes For convenience, Matrix m n α is defined as m → n → α , as this allows elements of the matrix to be accessed with A i j . However, it is not advisable to _co',
        pillar='SET', level=2, category='algebra',
        modulo='Mathlib.Data.Matrix', teoremas=665,
        dependencies=['mathlib-algebra-bigoperators', 'mathlib-algebra-order', 'mathlib-data-fin', 'mathlib-data-finset', 'mathlib-data-int', 'mathlib-data-nat'],
        keywords=['block', 'from', 'matrix', 'single', 'diagonal', 'linear', 'diag', 'transpose', 'blocks', 'apply', 'rows', 'cols', "diagonal'", 'zero', 'scalar', 'equiv', 'comp', 'monoid', 'symm', 'entry', "diag'", 'smul', 'left', 'right'],
    ),
    NodoCobertura(
        id='mathlib-data-fin',
        name='Data · Fin',
        description='The finite type with n elements Fin n is the type whose elements are natural numbers smaller than n . This file expands on the development in the core library. Main definitions finZeroElim : Elimination principle for the empty set Fin 0 , generalizes Fin.elim0 . Further definitio',
        pillar='SET', level=2, category='algebra',
        modulo='Mathlib.Data.Fin', teoremas=660,
        dependencies=['mathlib-algebra-bigoperators', 'mathlib-data-finset', 'mathlib-data-int', 'mathlib-data-nat', 'mathlib-logic-equiv', 'mathlib-order-interval'],
        keywords=['succ', 'cast', 'pred', 'above', 'zero', 'cons', 'last', 'even', 'injective', 'range', 'empty', 'self', 'apply', 'exists', 'order', 'append', 'left', 'right', 'congr', 'symm', 'head', 'alt0', 'alt1', 'equiv'],
    ),
    NodoCobertura(
        id='mathlib-logic-equiv',
        name='Logic · Equiv',
        description='Equivalence between types In this file we continue the work on equivalences begun in Mathlib/Logic/Equiv/Defs.lean , defining a lot of equivalences between various types and operations on these equivalences. More definitions of this kind can be found in other files. E.g., Mathlib',
        pillar='LOG', level=2, category='logic',
        modulo='Mathlib.Logic.Equiv', teoremas=659,
        dependencies=['mathlib-data-fin', 'mathlib-data-finset', 'mathlib-data-int', 'mathlib-data-multiset', 'mathlib-data-nat', 'mathlib-data-set'],
        keywords=['equiv', 'congr', 'apply', 'symm', 'subtype', 'sigma', 'swap', 'refl', 'right', 'trans', 'left', 'comp', 'arrow', 'unique', 'punit', 'self', 'extend', "congr'", 'perm', 'exists', 'embedding', 'bijective', 'injective', 'conj'],
    ),
    NodoCobertura(
        id='mathlib-data-ennreal',
        name='Data · ENNReal',
        description='Extended non-negative reals We define ENNReal = ℝ≥0∞ := WithTop ℝ≥0 to be the type of extended nonnegative real numbers, i.e., the interval [0, +∞] . This type is used as the codomain of a MeasureTheory.Measure , and of the extended distance edist in an EMetricSpace . In this fil',
        pillar='SET', level=2, category='algebra',
        modulo='Mathlib.Data.ENNReal', teoremas=649,
        dependencies=['mathlib-algebra-bigoperators', 'mathlib-algebra-order', 'mathlib-data-finset', 'mathlib-order-interval'],
        keywords=['nnreal', 'real', 'zero', 'exists', 'cast', 'zpow', 'cancel', 'right', 'smul', 'ennreal', 'forall', 'left', 'prod', 'order', 'union', 'self', 'half', 'finset', 'distrib', 'holder', "inv'", 'comm', "div'", 'apply'],
    ),
    NodoCobertura(
        id='mathlib-data-finsupp',
        name='Data · Finsupp',
        description='Miscellaneous definitions, lemmas, and constructions using finsupp Main declarations Finsupp.graph : the finset of input and output pairs with non-zero outputs. Finsupp.mapRange.equiv : Finsupp.mapRange as an equiv. Finsupp.mapDomain : maps the domain of a Finsupp by a function a',
        pillar='SET', level=2, category='algebra',
        modulo='Mathlib.Data.Finsupp', teoremas=617,
        dependencies=['mathlib-algebra-bigoperators', 'mathlib-algebra-order', 'mathlib-data-finset', 'mathlib-data-list', 'mathlib-data-multiset', 'mathlib-data-set'],
        keywords=['domain', 'finsupp', 'support', 'equiv', 'zero', 'apply', 'range', 'prod', 'multiset', 'filter', 'locus', 'single', 'subtype', 'symm', 'comap', 'finset', 'graph', 'curry', 'cons', 'lookup', 'left', 'card', 'injective', 'subset'],
    ),
    NodoCobertura(
        id='mathlib-linearalgebra-rootsystem',
        name='LinearAlgebra · RootSystem',
        description='Root data and root systems This file contains basic results for root systems and root data. Main definitions / results: RootPairing.ext : In characteristic zero if there is no torsion, the correspondence between roots and coroots is unique. RootSystem.ext : In characteristic zero',
        pillar='SET', level=2, category='algebra',
        modulo='Mathlib.LinearAlgebra.RootSystem', teoremas=590,
        dependencies=['mathlib-algebra-lie', 'mathlib-order-interval'],
        keywords=['root', 'reflection', 'coroot', 'chain', 'pairing', 'coeff', 'apply', 'span', 'perm', 'weight', 'equiv', 'coweight', 'zero', 'range', 'coreflection', 'cartan', 'matrix', 'smul', 'comp', 'support', 'flip', 'linear', 'self', 'base'],
    ),
    NodoCobertura(
        id='mathlib-grouptheory-groupaction',
        name='GroupTheory · GroupAction',
        description='Basic properties of group actions This file primarily concerns itself with orbits, stabilizers, and other objects defined in terms of actions. Despite this file being called basic , low-level helper lemmas for algebraic manipulation of • belong elsewhere. Main definitions MulActi',
        pillar='SET', level=2, category='algebra',
        modulo='Mathlib.GroupTheory.GroupAction', teoremas=566,
        dependencies=['mathlib-algebra-bigoperators', 'mathlib-algebra-order', 'mathlib-data-fin', 'mathlib-data-nat', 'mathlib-data-set'],
        keywords=['smul', 'orbit', 'stabilizer', 'fixed', 'subgroup', 'conj', 'block', 'pretransitive', 'action', 'multiply', 'fixing', 'equiv', 'apply', 'preprimitive', 'comp', 'points', 'card', 'submonoid', 'subset', 'disjoint', 'zero', 'quotient', 'embedding', 'univ'],
    ),
    NodoCobertura(
        id='mathlib-order-hom',
        name='Order · Hom',
        description='Order homomorphisms This file defines order homomorphisms, which are bundled monotone functions. A preorder homomorphism f : α →o β is a function α → β along with a proof that ∀ x y, x ≤ y → f x ≤ f y . Main definitions In this file we define the following bundled monotone maps: ',
        pillar='SET', level=2, category='set-theory',
        modulo='Mathlib.Order.Hom', teoremas=555,
        dependencies=['mathlib-data-finset', 'mathlib-data-set', 'mathlib-logic-equiv', 'mathlib-order-interval'],
        keywords=['comp', 'apply', 'dual', 'symm', 'order', 'copy', 'cancel', 'right', 'lattice', 'class', 'left', 'subtype', 'prod', 'embedding', 'assoc', 'mono', 'trans', 'bounded', 'ulift', 'refl', 'strict', 'equiv', 'preimage', 'monotone'],
    ),
    NodoCobertura(
        id='mathlib-ringtheory-powerseries',
        name='RingTheory · PowerSeries',
        description='Formal power series (in one variable) This file defines (univariate) formal power series and develops the basic properties of these objects. A formal power series is to a polynomial like an infinite sum is to a finite sum. Formal power series in one variable are defined from mult',
        pillar='SET', level=2, category='algebra',
        modulo='Mathlib.RingTheory.PowerSeries', teoremas=554,
        dependencies=['mathlib-algebra-mvpolynomial', 'mathlib-algebra-polynomial', 'mathlib-data-finsupp', 'mathlib-data-nat', 'mathlib-ringtheory-polynomial'],
        keywords=['coeff', 'order', 'zero', 'constant', 'derivative', 'unit', 'expand', 'series', 'monomial', 'rescale', 'ideal', 'xpow', 'eval₂', 'span', 'apply', 'smul', 'injective', 'eval', 'aeval', 'divided', 'prod', 'continuous', 'power', 'comp'],
    ),
    NodoCobertura(
        id='mathlib-topology-instances',
        name='Topology · Instances',
        description='topology instances: Ternary Cantor Set; Some results about the topology of ℂ; Instances related to the discrete topology; Topology on extended natural numbers; Topology on the integers; Topology of irrational numbers',
        pillar='SET', level=2, category='topology',
        modulo='Mathlib.Topology.Instances', teoremas=554,
        dependencies=['mathlib-algebra-bigoperators', 'mathlib-algebra-order', 'mathlib-analysis-complex', 'mathlib-data-ennreal', 'mathlib-data-int', 'mathlib-data-nat'],
        keywords=['continuous', 'matrix', 'nhds', 'tendsto', 'cantor', 'zero', 'real', 'equiv', 'cast', 'dist', 'lift', 'embedding', 'closed', 'block', 'circle', 'const', 'uniform', 'order', 'eventually', 'apply', 'nnreal', 'liminf', 'ball', 'transpose'],
    ),
    NodoCobertura(
        id='mathlib-ringtheory-localization',
        name='RingTheory · Localization',
        description='Localizations of commutative rings This file contains various basic results on localizations. We characterize the localization of a commutative ring R at a submonoid M up to isomorphism; that is, a commutative ring S is the localization of R at M iff we can find a ring homomorphi',
        pillar='SET', level=2, category='algebra',
        modulo='Mathlib.RingTheory.Localization', teoremas=551,
        dependencies=['mathlib-algebra-bigoperators', 'mathlib-algebra-order'],
        keywords=['equiv', 'localization', 'ring', 'algebra', 'lift', 'zero', 'integer', 'field', 'integral', 'injective', 'fraction', 'exists', 'apply', 'submonoid', 'surjective', 'tensor', 'smul', 'normalization', 'comp', 'divisors', 'multiple', 'span', 'range', 'symm'],
    ),
    NodoCobertura(
        id='mathlib-linearalgebra-tensorproduct',
        name='LinearAlgebra · TensorProduct',
        description='Universal property of the tensor product Given any bilinear map f : M →ₛₗ[σ₁₂] N →ₛₗ[σ₁₂] P₂ , there is a unique semilinear map TensorProduct.lift f : TensorProduct R M N →ₛₗ[σ₁₂] P₂ whose composition with the canonical bilinear map TensorProduct.mk is the given bilinear map f . ',
        pillar='SET', level=2, category='algebra',
        modulo='Mathlib.LinearAlgebra.TensorProduct', teoremas=546,
        dependencies=['mathlib-data-int'],
        keywords=['tensor', 'tmul', 'right', 'equiv', 'apply', 'comm', 'symm', 'comp', 'smul', 'left', 'quot', 'basis', 'inverse', 'trans', 'assoc', 'congr', 'finsupp', 'quotient', 'lift', 'exists', 'direct', 'limit', 'range', 'zero'],
    ),
    NodoCobertura(
        id='mathlib-topology-continuousmap',
        name='Topology · ContinuousMap',
        description='Continuous bundled maps In this file we define the type ContinuousMap of continuous bundled maps. We use the DFunLike design, so each type of morphisms has a companion typeclass which is meant to be satisfied by itself and all stricter types.',
        pillar='SET', level=2, category='topology',
        modulo='Mathlib.Topology.ContinuousMap', teoremas=541,
        dependencies=['mathlib-algebra-order', 'mathlib-algebra-star', 'mathlib-analysis-complex', 'mathlib-analysis-specialfunctions', 'mathlib-data-set', 'mathlib-topology-order'],
        keywords=['continuous', 'apply', 'comp', 'linear', 'ideal', 'compact', 'norm', 'nnreal', 'real', 'equiv', 'left', 'dist', 'smul', 'bounded', 'part', 'eval', 'const', 'lift', 'compactly', 'supported', 'copy', 'isometry', 'zero', 'concat'],
    ),
    NodoCobertura(
        id='mathlib-algebraictopology-simplicialset',
        name='AlgebraicTopology · SimplicialSet',
        description='Simplicial sets A simplicial set is just a simplicial object in Type , i.e. a Type -valued presheaf on the simplex category. (One might be tempted to call these "simplicial types" when working in type-theoretic foundations, but this would be unnecessarily confusing given the exis',
        pillar='SET', level=2, category='topology',
        modulo='Mathlib.AlgebraicTopology.SimplicialSet', teoremas=520,
        dependencies=['mathlib-categorytheory-limits', 'mathlib-categorytheory-monoidal', 'mathlib-data-fin', 'mathlib-logic-equiv'],
        keywords=['comp', 'degenerate', 'nerve', 'functor', 'edge', 'inverse', 'equiv', 'dimension', 'apply', 'simplex', 'homotopy', 'category', 'finite', 'prod', 'right', 'mono', 'exists', 'tensor', 'truncated', 'lift', 'zero', 'multicofork', 'desc', 'range'],
    ),
    NodoCobertura(
        id='mathlib-numbertheory-modularforms',
        name='NumberTheory · ModularForms',
        description='Modular forms This file defines modular forms and proves some basic properties about them. Including constructing the graded ring of modular forms. We begin by defining modular forms and cusp forms as extension of SlashInvariantForm s then we define the space of modular forms, cu',
        pillar='SET', level=2, category='number-theory',
        modulo='Mathlib.NumberTheory.ModularForms', teoremas=514,
        dependencies=['mathlib-analysis-asymptotics', 'mathlib-analysis-complex', 'mathlib-analysis-specialfunctions', 'mathlib-order-interval', 'mathlib-ringtheory-localization', 'mathlib-ringtheory-powerseries'],
        keywords=['zero', 'slash', 'infty', 'cusp', 'apply', 'gamma', 'expansion', 'strict', 'smul', 'periods', 'width', 'function', 'invariant', 'exists', 'petersson', 'const', 'series', 'conj', 'adjoin', 'form', 'norm', 'deriv', 'comp', 'decay'],
    ),
    NodoCobertura(
        id='mathlib-data-int',
        name='Data · Int',
        description='Basic operations on the integers This file builds on Data.Int.Init by adding basic lemmas on integers. depending on Mathlib definitions.',
        pillar='SET', level=2, category='algebra',
        modulo='Mathlib.Data.Int', teoremas=510,
        dependencies=['mathlib-algebra-order', 'mathlib-data-nat', 'mathlib-data-set', 'mathlib-order-interval'],
        keywords=['right', 'succ', 'left', 'cast', 'zero', 'card', 'clog', 'modulus', 'shift', 'bodd', 'filter', 'zpow', 'self', 'exists', 'pred', 'induction', 'bitwise', 'test', 'xgcd', 'greatest', 'least', 'coprime', 'nonneg', 'emod'],
    ),
    NodoCobertura(
        id='mathlib-probability-independence',
        name='Probability · Independence',
        description='Independence of sets of sets and measure spaces (σ-algebras) A family of sets of sets π : ι → Set (Set Ω) is independent with respect to a measure μ if for any finite set of indices s = {i_1, ..., i_n} , for any sets f i_1 ∈ π i_1, ..., f i_n ∈ π i_n , μ (⋂ i in s, f i) = ∏ i ∈ s',
        pillar='SET', level=2, category='probability',
        modulo='Mathlib.Probability.Independence', teoremas=500,
        dependencies=['mathlib-measuretheory-integral'],
        keywords=['indep', 'cond', 'prod', 'sets', 'inter', 'process', 'right', 'left', 'limsup', 'measure', 'zero', 'char', 'precomp', 'union', 'lintegral', 'congr', 'self', 'meas', 'measurable', 'singleton', 'integral', 'generate', 'from', 'comap'],
    ),
]
